// <auto-generated />
namespace TimeTrackr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class renametotask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renametotask));
        
        string IMigrationMetadata.Id
        {
            get { return "201308140000299_renametotask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
