// <auto-generated />
namespace TimeTrackr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixedkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201308160142298_fixedkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
