// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Validators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validators));
        
        string IMigrationMetadata.Id
        {
            get { return "201307150559141_Validators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
