// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRAtingMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRAtingMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201307150555445_AddRAtingMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
